/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_BitMapFactory */

#ifndef _Included_jni_BitMapFactory
#define _Included_jni_BitMapFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_BitMapFactory
 * Method:    axv2BitMaps
 * Signature: (Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_jni_BitMapFactory_axv2BitMaps
  (JNIEnv *, jobject, jstring, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
